### ISSUE TITLE
Compiling on older Ubuntu. 

### ISSUE THREAD

**Issue by rewolff** [mnencia/mchfuse#12]
On Ubuntu 18.04 we had the problem that we had to "go get" all the dependencies manually. 
Also, the "go get github.com/hanwen/go-fuse/v2/fs" didn't work. We removed the "v2" in the "go get" command and also in a bunch of places in the sources. I could provide a pull request.... but: it seems this was unnecessary on ubuntu 20.04, so maybe you want to decide: that's too old, not supported, don't do that then. 
The go on 18.04 did not recognize %w keywords in the error messages. Changed to %v the package compiled. 

On ubuntu 16.04 we couldn't get it to compile at all. We just copied the compiled binary from 18.04. 

Just FYI: If you want to decide: " Whoa, way too old, not going to bother with that" , then that's fine with me... .

**Comment by mnencia** [comment]
Hi Roger, thank you for the report.

To build this software, you need at least go 1.13 because I used several features introduced in that version. With go [is easy to compile for a different OS/architecture](https://www.digitalocean.com/community/tutorials/how-to-build-go-executables-for-multiple-platforms-on-ubuntu-16-04), so it is not even required to be on the same operating system to build an executable for the target machine. I do not see any substantial improvement by supporting older releases of the language, so I'd avoid doing any change in that direction unless someone has a strong reason to do it.

Moreover, you can install the latest release pre-built binary using the [installation script](https://github.com/mnencia/mchfuse#user-content-installing-the-latest-release).
